Education=["study",
"school",
"book",
"book",
"book advance",
"book medium",
"book paperwork",
"book periodics",
"book purchase",
"book purchasing",
"book read",
"book sale",
"booking",
"bookpk",
"booksbagsstationaory",
"bookspk",
"career education",
"child education",
"child education fee",
"coach",
"coach academy",
"coach class",
"computer tution",
"daewoo photocopy",
"deen education",
"education",
"education ayeshs",
"education book purchase",
"education bs",
"education career",
"education job",
"education learn",
"education schol qaida",
"education school",
"educational",
"educational expense",
"edugate school use",
"fee star school",
"future school system",
"hadi school fee",
"haris education",
"intellect tutor academy",
"isaiah school van",
"kid school",
"law study",
"leader school",
"medical book",
"musa education",
"other school stuff",
"personal expense university",
"photo",
"photo copy",
"photo state",
"photocopier",
"photocopy",
"photostat",
"photostate",
"print photocopy",
"quran education",
"rumman education",
"school",
"school book uniform",
"school canteen",
"school child",
"school deposit",
"school equipment",
"school expense",
"school expensis",
"school faiq",
"school fee",
"school fee other",
"school fund",
"school other",
"school others",
"school transport",
"school van",
"school",
"school system",
"star high school",
"stationary photocopy",
"student",
"student admission",
"student exchange",
"student fee",
"study",
"study expense",
"study pack",
"teach",
"teacher",
"teacher fee",
"teacher pay",
"tution",
"tution fee",
"tution fee collection",
"tution fes",
"tution payment",
"tutions",
"university",
"university fee",
"university ",
"university town",
"university "
]

