Education=["study",
"school",
"book",
"courses",           
"college",
"booking",
"bookpk",
"booksbagsstationaory",
"bookspk",
"career education",
"child education fee",
"coach",
"coach academy",
"coach class",
"computer tution",
"education school",
"educational",
"school",
"education",
"tutor",
"law study",
"university",
"photocopier",
"photocopy",
"photostat",
"photostate",
"print photocopy",
"quran education",
"school book uniform",
"school transport",
"stationary photocopy",
"student",
"study",
"teach",
"teacher",
"tution",
"tutions",
"university",
"university fee",
"univarcity",
"univercity"
]
