Eating_out=["food and drinks",
"dinner",
"lunch/dinner/bfast/snk",
"dinner/ bk hotel",
"vhr dinner",
"dinnerr",
"broast",
 "pizza",
"sandwhich",
 "tikka",
 "boti",            
"lunch / dinner",
"eating-",
"eating-out/ food expense",
"eating-out",
"eatingout",                        
"food/snacks/eating out",
"chips and eating",
"officelunch",
"school lunch",
"university lunch",
"club lunch",
"lunch & snacks",
"daily lunch or breakfast",
"food item",
"foods",
"food",
"burger",
"burger bun",
"fries",
"ketchup fries",
"fries masala",
"tea",
"lipton tea",
"milk & tea",
"nashta+tea",
"pakroa + tea",
"tea & biscuit",
"tea & juices",
"tea & milk & sugar &water",
"tea bua ji",
"tea and baryani",
"tea and milk",
"tea n peanuts",
"tea2",
"tokla tea",
"chai",
"chai shai",
"breakfast",
"break fast",
"breakfast items",
"nashta",
"nashta + khana",
"hotel",
"hotels",
" khaana peena",,
"canteen bil",
"canteen",
"canten",
"cainteen"
            




]
