Food_and_Drink={

    "Food Times":("breakfast",
                  "break fast",
                  "nashta",
                  "nashtaa",
                  "brunch",
                  "lunch",
                  "hi tea",
                  "hi-tea",
                  "snacks"
                  "hitea",
                  "dinner",
                  "diner"),


    "Resturants":("kfc",
                  "mcdonels",
                  "mc donels",
                  "hardees",
                  "pizzahut",
                  "pizza hut",
                  "burgerlab",
                  "burger lab",
                  "burger o clock",
                  "oh my grill",
                  "omg",
                  "vintage",
                  "burger king"
                  "california",
                  "bigbash",
                  "14th street",
                  "the sauce",
                  "ridaan",
                  "koffie chalet",
                  "figaro grill",
                  "optp",
                  "new york pizza",
                  "sajjad",
                  "grill o",
                  "pow",
                  "sobremesa",
                  "figaro grill",
                  "broadway",
                  "subway",
                  "sub way",
                  "ginsoy",
                  "kababjees",
                  "kabaab jees",
                  "kabab jees",
                  "kolachi",
                  "charcoal",
                  "pizza point",
                  "pizzapoint",
                  "gloria jeans",
                  "gloriajeans",
                  "nandoos",
                  "kaybees",
                  "chupal",
                  "chaupal",
                  "rossati",
                  "dominos",
                  "salt and pepper",
                  "bar b q tonight",
                  "bbq tonignt",
                  ""),
    "Food":("eat",
            "eating",
            "khana",
            "khanna",
            "eating-out",
            "eating out",
            "burger",
            "bun kabab",
            "fries",
            "pizza",
            "tikka",
            "broast",
            "chips",
            "cookies",
            "kabab",
            "kabaab",
            "chaat",
            "golgappay",
            "gol gapay",
            "pizza fries",
            "cheeze",
            "ice cream",
            "icecream",
            "gola ganda",
            "cone",
            "mcflurry",
            "tea",
            "chai",
            "chaye",
            "chinees",
            "stakes",
            "sandwhich",
            "sand which",
            "haandi",
            "malai boti",
            "karahi",
            "boti",
            "sharbat",
            "juices",
            "kava",
            "kasmeri chai",
            "karak chai",
            "dairymilk chai",
            "zinger burger",
            "junk food"
            "biscuit",
            "cake",
            "briyani",
            "bryani",
            "nihari",
            "rolls",
            "shawarma",
            "shami burger"),

    "Drinks":("colddrinks",
              "cold drinks",
              "soft drinks",
              "coke",
              "pepsi",
              "7up",
              "dew",
              "mirinda",
              "fanta",
              "cola",
              "tang",
              "juices",
              "sprite",
              "coka cola",
              "cokacola",
              "drinks",
              "redbull",
              "viskey",
              "coffee",
              "cappacino",
              "Cappuccino",
              "latte",
              "lemonate",
              "lassi",
              "soda",
              "rooh afza",
              "roohafza",
              "jam-e-shirin"
              "slice",
              "alcohal",
              "visky",
              "brandy",
             "cocktail",
              "beer",
              "vine",
              "daroo",
              "sharaab",
              "hard drink",
              "harddrink",

              )





    }
