Eating_out=["food and drinks",
"dinner",
"out dinner",
"office dinner",
"lunch/dinner/bfast/snk",
"dinner/ bk hotel",
"eating-out dinner",
"outing and dinners",
"vhr dinner",
"dinnerr",
"lunch dinner",
"breakfast & dinner",
"lunch / dinner",
"eating-out",
"eating",
"eating out uni",
"eating out",
"eating-",
"eating-out/ food expense",
"food & eating-out",
"eating-out friends",
"normal eating",
"dg khan eating",
"entertaintment eating-out",
"eating-out with sani",
"eating-out and entertainment",
"eating out with friends",
"eating-out with family",
"eating cas",
"eating in",
"eating foods",
"friends eating",
"office eating",
"eating-out & sheesha",
"eating-cas",
"personal eating",
"eating-monthly out",
"office eating-out",
"eating-drinking out",
"eating-out / other",
"eating-out family",
"eating lunch",
"eating-out casual",
"food & eating out",
"eating-out with friends",
"eating out with family",
"eating and beverage-out",
"eating-out (family)",
"ahl eating-out",
"daily eating",
"eating - take out",
"eating office",
"eating- (own +family fun)",
"eating_casual",
"food/snacks/eating out",
"naeem eating",
"outside eating",
"chips and eating",
"eating-out wali salma",
"r.k eating out etc",
"university eating out",
"eating (anchol)",
"eating out -artt",
"eating out with noor",
"eating sp",
"eating-in",
"eating-out with guest",
"leave eating",
"lunch, eating out",
"friends eating out",
"office eating out",
"own eating exp",
"eating out f",
"eating out with frnd",
"eating outside",
"eating-out food",
"family eating out",
"simple eating",
"lunch",
"office lunch",
"offc lunch",
"lunch funds",
"officelunch",
"school lunch",
"university lunch",
"club lunch",
"lunch & snacks",
"daily lunch or breakfast",
"lunch (office)",
"office lunch / fare",
"out lunch",
"office lunch didi",
"lunch office",
"lunch at client",
"college lunch",
"lunch at uni",
"office lunch and tea",
"lunch / other",
"office lunch others",
"breakfast, water and lunch at work",
"daily lunch",
"work lunch",
"lunch time",
"fare + lunch",
"kids school lunch",
"lunch subsidy",
"official lunch",
"bank muscat lunch",
"kids lunch",
"lunch imran",
"lunch at firm",
"lunch kausar & ali",
"office lunch and others",
"office lunch exp",
"vhr lunch",
"lunch exp",
"staff lunch",
"tag lunch",
"outing",
"outing/travelling",
"family outing",
"office outing",
"outing with wife",
"outing picnic",
"outing family",
"family outings",
"outing ..",
"outing tour",
"outing with friends",
"outings",
"hareem outing",
"daily outing",
"food",
"food item",
"staff food",
"lahore ldc (food & bev)",
"lhe-food expenses",
"fooding",
"food expenses",
"office food",
"reg. food",
"foods",
"workplace food",
"food shopping",
"fuel/food",
"junk food",
"fast food",
"food home delivery",
"food items",
"hotel food",
"food and drink",
"hassan food",
"food & beverages",
"ammar food",
"monthly food + room exps",
"food & drinks",
"foodstuffs",
"food cost personal",
"gym food",
"foodbill",
"healthy food",
"room food",
"personal food",
"for food",
"self food",
"food at office",
"food general",
"food/snacks/water",
"labar food drink",
"vaja-pora-fast-food",
"daily food exp",
"food exp",
"house food items",
"office break food",
"college food",
"house food",
"ordered food",
"university food",
"cat food",
"food daily",
"food hostel",
"food office",
"food & drinks,",
"food for consumption",
"misc food items",
"non food shopping",
"other foods",
"trish food",
"ali raza foods & pampers accessories",
"food and beverage",
"fooding office",
"foods daily",
"haider food",
"preshay food and nutrition",
"street food",
"uni food",
"food tansport",
"hostel food",
"bring food home",
"food cost other",
"other food exp.",
"zomato food order",
"dofood: everydayeats",
"food etc",
"kheljee foods",
"light food",
"airport food",
"ali raza food & toys",
"cow food",
"fast-food",
"food / transport",
"food outside",
"food and beverages",
"food from outside",
"hmdlvfood",
"mix(med/load/food)",
"parents fooding",
"restaurant + food",
"at home outside food",
"club food",
"daily food items",
"food expense",
"other food expenses",
"ali raza foods & pampers",
"food & snacks",
"food ingredients",
"food.sabzee",
"foods & drinks",
"outside food",
"daily food",
"food (mess)",
"baby food",
"daily food expense",
"food and drinks with friends",
"food at a.jamal",
"foodies",
"hotel & fast-food",
"juck food",
"snacks & food",
"daily food income",
"dofood: occasional eats",
"extra expense for food",
"faisal foods",
"fast foods",
"fish food",
"food allowance",
"food claim",
"food service",
"food at work",
"food delivery",
"food party",
"good food",
"hotel and food expense",
"hotel fare with food",
"john food",
"kids food & toys",
"non-food",
"office food expenses",
"p: rent & food",
"share food",
"small foods",
"night food",
"daily foods",
"extra food",
"burger",
"burger bun",
"olive burger",
"hot dog burger",
"burger n soda",
"burger's samaan",
"burger's sale",
"burger 21",
"fries",
"ketchup fries",
"fries box",
"fries masala",
"fries garlic mayo and buffalo",
"fries+pizza",
"french fries",
"tea",
"tea shop",
"office tea",
"tea break",
"tea bar",
"tea / refreshment",
"cigarettes & tea",
"tea/coffee",
"tea club",
"green tea",
"team",
"coffee and tea",
"tea coffee",
"tea snacks",
"teabar",
"tea time",
"ccr tea",
"cigarette tea",
"0ffice tea & canteen",
"tea and etc",
"tea/refreshment",
"tea ta",
"tea + meal",
"tea too",
"tea and biscuits",
"tea cigrate",
"brackfast / tea",
"cigarette and tea",
"office tea, entainnt, misc. expenses",
"tea items",
"chaaye tea latte gloria",
"tea & coffee",
"office tea expences",
"tea and coffee",
"piling team",
"tea/coffee/juices",
"mad tea",
"tea /coffee",
"tea exp",
"office tea & refreshment",
"tea and other expense",
"tea out",
"tea saman",
"ciggiy and tea",
"drinking tea & coffee",
"hi tea",
"office tea & refreshments",
"tea & snack",
"tea & snacks",
"tea at mill",
"tea snack",
"tea somok",
"tea./coffee",
"tea/ice/water",
"tea/coffee/icecream",
"mtbc tea breaks",
"tea mess",
"tea-lunch",
"advance pay mess tea",
"evening tea stuff",
"office tea break",
"tea allowance",
"tea allownce",
"tea and gutkha",
"tea biscuit",
"tea coffe",
"tea stall",
"tea and cigarettes",
"tea milk",
"tea n lunch",
"tea or coffee",
"tea(other masala too)",
"tea,milk",
"teabar bill",
"team expenses (receivable)",
"team lunch",
"21 lunch & tea",
"ammi rice/tea",
"chai teas",
"cigarette & tea",
"coffee / tea",
"cold drinks and tea",
"dinner and tea",
"due tea stall",
"etea",
"flat tea & snacks",
"greentea",
"hotel tea",
"lipton tea",
"milk & tea",
"mojo teal",
"nashta+tea",
"office (tea)/water",
"office expense-food team",
"pakro + tea",
"pakroa + tea",
"red tea",
"school tea package",
"shab e barat plus tea",
"staff tea",
"tea & biscuit",
"tea & juices",
"tea & milk & sugar &water",
"tea 7 baje",
"tea bar n falcon mart",
"tea bill",
"tea brake",
"tea bua ji",
"tea for guest",
"tea income",
"tea office",
"tea personal",
"tea and baryani",
"tea and milk",
"tea bar and mess",
"tea bar tax",
"tea biskat",
"tea box",
"tea chaaaie",
"tea etc",
"tea material",
"tea n peanuts",
"tea pack",
"tea/coffe",
"tea2",
"team loan (receivable)",
"team party",
"toll gatea",
"umbrella & tea",
"tea @ milk",
"teag",
"team expenses",
"tokla tea",
"chai",
"chai sutta",
"chai shai",
"chairty",
"office chai pani kharcha",
"rozmarrah chai shai",
"chairity exp",
"office chai pani",
"chai pani",
"chaild",
"chai/sutta",
"chaii",
"office chai",
"thadi/chai/sutta",
"chairman",
"kana nd chai",
"category",
"cigarettes",
"cigarette",
"cig",
"cigrate",
"cigrette",
"cigratte",
"cigs",
"cigrates",
"cigrettes",
"cigerate",
"cigerette",
"cigrattes",
"cigrat",
"cigarate",
"cigg",
"cigeratte",
"cigret",
"ciggerete",
"cigerattes",
"cigrete",
"ciggrate",
"cigar",
"cigaret",
"ciggerate",
"ciggrette",
"ciggarette",
"cigreat",
"cigrets",
"cigarrettes",
"cigrt",
"ciggarates",
"cigerates",
"cigerettes",
"cigerrate",
"cigaros",
"cig.",
"cigarettes,  pan and chalia",
"cigerets",
"cigs+refreshments",
"cigruite",
"ciggerettes.",
"cigrt naswar",
"cigrute",
"pan ciggrate",
"cigarettes & alcohol",
"my cigrate",
"ciggs",
"alcohol & cigerattes",
"meds and cigs",
"personal cig n drnk",
"cigerrete",
"cigx",
"cig & bottle",
"ciggeretes",
"cigarettes and chewinggums",
"cigratsss",
"alcohol & cigarettes",
"cigarett",
"cigeretes",
"cigs n stuff",
"cig bottle",
"cigarrette",
"ciggrte",
"cig & drinks",
"cigerats",
"ciggaretes",
"ciggis",
"ciggratte",
"cigreete",
"cigrtee",
"cigsrettes",
"sutta",
"suttay",
"suts",
"breakfast",
"break fast",
"break",
"daily breakfast",
"breakfast items",
"breakfast/lnh",
"breakfast meal",
"section break",
"break first",
"office breakfast",
"break fast.",
"breakfast expense",
"breakfast/hotel",
"milk breakfast",
"morning breakfast",
"vhr breakfast",
"nashta",
"nasha",
"nashta + khana",
"nashtaa",
"nashay",
"breasfast / nashta",
"nashta khana",
"lunch at office",
"hazi lunch",
"labour lunch",
"lunch & conveyance",
"lunch at artt",
"lunch at job",
"lunch expence",
"office- lunch",
"smoking",
"hotel",
"hotels",
"hotel stay",
"hoteling",
"canteen",
"canteen khaana peena",
"college canteen",
"canteen purchases",
"canteen bil",
"nsu canteen",
"canteen exp",
"canteen-sbp",
"uni canteen",
"dolmen canteen",
"ku canteen",
"bty canteen",
"canteen opf",




]