Fuel_Maintainance=["bayik petrol",
"bike",
"bike alteration",
"bike car repair",
"bike car service",
"bike car service repair",
"bike cc",
"bike copy",
"bike earnings",
"bike feul",
"bike fuel",
"bike fuel maintenance",
"bike fuel n other",
"bike general",
"bike handle",
"bike kec",
"bike kharcha",
"bike lease",
"bike lhr",
"bike lock",
"bike maint",
"bike maintainance",
"bike maintenance",
"bike maintenance fuel",
"bike maitainance",
"bike mantainenc",
"bike mantenance",
"bike mantinance",
"bike mazdoori",
"bike mechanic",
"bike mentainance",
"bike mentinance",
"bike mentinence",
"bike mentinense",
"bike mnt",
"bike oil",
"bike oil change",
"bike oile",
"bike parking",
"bike patral",
"bike patrol",
"bike patrol maintenance",
"bike perchi",
"bike petrol",
"bike petrol maintainence",
"bike petrol maintenance",
"bike puncher",
"bike puncture",
"bike r",
"bike rent",
"bike repair",
"bike repair miantenance",
"bike repair n service",
"bike repaire",
"bike reparing",
"bike ride",
"bike sale",
"bike service",
"bike tax",
"bike token stand",
"bike tube",
"bike tune",
"bike tune petrol",
"bike tunning",
"bike tunning service",
"bike tyer",
"bike wash",
"bike work",
"car",
"car ac",
"car ac condensor gas petrol mat",
"car accesories",
"car accessory",
"car air pressure",
"car allowance",
"car auto gear",
"car battery",
"car bike",
"car bike maintenance",
"car bike mentanace",
"car bike mentinance",
"car bike service",
"car business",
"car buy",
"car care",
"car chamber repair",
"car clean",
"car cleaner",
"car cleaning",
"car cng",
"car cng share friend",
"car contribution",
"car earn",
"car emi",
"car engine oil",
"car equipment",
"car fare",
"car fare school",
"car feul",
"car finance",
"car financial",
"car fine ticket",
"car fit",
"car fitness",
"car fix",
"car fuel",
"car fuel maintenance",
"car fuel repair",
"car fuel transport",
"car fule",
"car gas",
"car horn",
"car ijarah",
"car inst",
"car insurance",
"car item purchase",
"car lease",
"car machnic",
"car mainntainance",
"car maint",
"car maint n",
"car maintain",
"car maintainace",
"car maintainance",
"car maintainance fuel",
"car maintaine",
"car maintainence",
"car maintainence fuel",
"car maintaines",
"car maintains",
"car maintanace",
"car maintanance",
"car maintance",
"car maintanence",
"car maintenance",
"car maintenance fuel",
"car maintenance n fuel",
"car maintenance sensor wire",
"car maintenance swift",
"car maintenancr",
"car maintinace",
"car maintinance",
"car maintrnsn e",
"car maker",
"car man",
"car manganese",
"car mantainace",
"car mantainance",
"car mantainence",
"car mantinace petrol",
"car mantinance",
"car mantines",
"car material",
"car mechanic",
"car mechanical",
"car meintenanse repair",
"car ment",
"car mentenance",
"car mentinance",
"car mentinence",
"car mintenance",
"car misc",
"car mlaintence",
"car mnt",
"car motorcycle petrol",
"car n bike",
"car oil",
"car oil change",
"car others",
"car overhaul",
"car pancture",
"car park clean",
"car parking",
"car parking cost",
"car parking ticket",
"car part",
"car patrol",
"car payment",
"car perk",
"car petrol",
"car petty",
"car pol",
"car pool",
"car purchase",
"car ramp clean",
"car reair cash",
"car refuel",
"car registeration",
"car rent",
"car rental",
"car rep",
"car repair",
"car repair bill tay",
"car repair maint",
"car repair repayment",
"car repaire",
"car reparing",
"car repearing",
"car return",
"car run",
"car sale",
"car sale amount",
"car sav",
"car save",
"car seat cover",
"car sell",
"car service",
"car service rent",
"car service repair charge",
"car service tecno",
"car servicin",
"car tape",
"car tape ballenoo",
"car thek karai",
"car token tax",
"car training",
"car trip",
"car tune",
"car tunning",
"car tyre",
"car tyre air",
"car wash",
"car wash maintenance",
"car wash mali",
"car wash puncture",
"car wash salary",
"car wash service",
"car washer",
"car work",
"car xli",
"carcare",

"care cargo",
"care maintance",
"careem khizer c",
"cargo",
"cargo curriours",

"carolla",
"carpet",
"carry",
"cartage",
"carwash",
"city fuel",
"city petrol",
"cng",
"cng car",
"cng fill sentro",
"cng fuel",
"cng honda lunce",
"cng oil",
"cng petrol",
"cng sett abu",
"cng tax",
"company fuel",
"conte petrol",
"corola fuel maintenance",
"corolla fuel",
"bike earn",
"fuel",
"diesel n petrol",
"engine oil",
"factory fuel",
"feul bike",
"fit fuel",
"fuel",
"fuel allowance",
"fuel allownce",
"fuel bike",
"fuel bike maintenance",
"fuel car",
"fuel card",
"fuel cash",
"fuel charge",
"fuel city",
"fuel cng",
"fuel company",
"fuel compensation",
"fuel corolla",
"fuel cuore car",
"fuel diesel",
"fuel distribution",
"fuel",
"fuel fit",
"fuel generater",
"fuel honda",
"fuel lubricant",
"fuel maintenance",
"fuel maintenance bike",
"fuel maintenance car",
"fuel mantainase",
"fuel medical",
"fuel mehran",
"fuel motorcycle",
"fuel office",
"fuel petrol",
"fuel purpose bike maintance",
"fuel receive",
"fuel refund",
"fuel reimbursement",
"fuel sprinter bike",
"fuel",
"fuel  bike maint",
"fuel  bke",
"fuel car maintenance",
"fuel  maintainance",
"fuel maintenance",
"fuel",
"fuel travel",
"fuel unique bike",
"fuel vehicle maintenance",
"fule bike service",
"fule disel petrol",
"gari",
"gen petrol",
"generator petrol",
"gjw bike",
"hispeed petrol",
"home fuel travel",
"honda city fuel",
"hyd nw fuel toll",
"lhr bike",
"liana fuel",
"maintainance",
"maintanance",
"maintenance",
"mehran fuel",
"mehran fuel maintenance",
"mehran petrol",
"motor bike",
"motor bike repair",
"motorbike",
"motorbike parking",
"motorbike repair",
"motorcycle fuel",
"my fuel",
"my hyundai fuel",
"new motorbike",
"oil change",
"oil change car",
"oil change service",
"other income cng",
"pathao bike drive",
"patrol",
"patrol charge",
"patrol mobil",
"personel bike",
"petrol",
"petrol",
"petrol bike",
"petrol bike maintainence",
"petrol bike tune",
"petrol car",
"petrol car bike",
"petrol car maintainance",
"petrol cng",
"petrol cycle",
"petrol deisel gas",
"petrol field",
"petrol fill",
"petrol fill sentro",
"petrol genretor",
"petrol mantance",
"petrol motor cycle repair",
"petrol office",
"petrol personal",
"petrol q",
"petrol salary",
"petrol save",
"petrol service",
"petrol transport",
"petrole",
"petroleum",
"petroll",
"pettol bike fuel",
"r bike",
"repair bike",
"repair maint",
"repair maintenance",
"repair n maintenance",
"patrol",
"super power fuel",
"suzuki cultus repair oil change",
"suzuki faw petrol",
"suzuki petrol",
"tahir fuel",
"bike",
"fuel",
"patrol",
"petrol",
"fuel",
"tune bike",
"usman city petrol",
"vehical petrol",
"vehicle fuel",
"vehicle maintenance",
"wagonr fuel"

]