Fuel_and_Maintenance={ 
  
  "Fuel":(                      "fuel",
                                "feul",
                                "petrol",
                                "patrol",
                                "patral",
                                "ptrol",
                                "cng",
                                "petrol and cng",
                                "gas and petrol",
                                "gasoline",
                                "diseal",
                                "lpg",
                                "desal",
                                "octane",
                                "high octane",
                                "octain",
                                ),
"Maintenance":("car service",
                "bike service",
               "new key",
                "wash",
                "tuning",
                "puncture",
                "maintainance",
               "maintenance",
                "tyre",
               "tyer",
               "repaint car",
                "cylinder",
                "car a/c",
                "central locking",
                "engine",
                "baterry",
                "stearing",
                "bettry",
               "battery"
                "radiator",
                "viper",
                "polish",
               "a/c",
               "AC",
               "auto",
                "ribbon polish",
                "dentor",
                "paint",
                "painter",
                "head light",
               "headlight",
               "backlight",
               "car parts",
               "fix",
                "back light",
                "fogg light",
                "indicator",
                "suspention",
                "modification",
                "gadgets",
                "air pressure",
                "mileage",
                "car theek karai",
                "seat cover",
                "dashboard",
                "engen",
                "plugs",
                "shocks",
                "oil",
                "oil filter",
                "brakes",
                "car mats",
                "gear",
                "fix",
                "tape",
                "woffers",
                "maintenence",
                "maintainence",
                "car clean",
                "car overhaul",
                "motorbike repair",
                "mechanic",
                "mechanik",
                "macanic",
                "system",
                "amplifier",
                "repairing",
                "repair",
                "bike mazdoori"

                )

}
