Fuel_Maintainance=["bayik petrol",
"bike",
"bike alteration",
"bike car repair",
"bike car service",
"bike earnings",
"bike feul",
"bike general",
"bike fuel",
"bike mazdoori",
"bike mechanic",
"bike mnt",
"bike oil",
"bike patral",
"bike patrol",
"bike petrol maintainence",
"bike puncher",
"bike puncture",
"bike tune petrol",
"bike tunning",
"bike tyer",
"car",
"car ac",
"car accesories",
"car auto gear",
"car battery",
"car bike",
"car bike maintenance",
"car bike mentanace",
"car bike mentinance",
"car clean",
"car cng",
"car feul",
"car fix",
"car fuel",
"car fuel maintenance",
"car gas",
"car machnic",
"car maintain",
"car maintainace",
"car maintainance",

"car mlaintence",
"car others",
"car overhaul",
"car pancture",
"car parking ticket",
"car patrol",
"car service",
"car tape",
"car tape ballenoo",
"car thek karai",
"car tune",
"car tunning",
"car tyre",
"car tyre air",
"car wash",
"car xli",
"care cargo",
"carolla",
"cng",
"cng tax",
"diesel n petrol",
"diseal",
"engine oil",
"fuel bike",
"fuel mantainase",
"fuel motorcycle",
"fuel vehicle maintenance",
"disel",
"motorbike",
"motorbike parking",
"motorbike repair",
"petrol",
"petrol",
"petrol cng",
"petrol deisel gas",
"petrol motor cycle repair",
"petrole",
"petroleum",
"patrol",
"vehical petrol",
"vehicle fuel",
"vehicle maintenance",
"wagonr fuel"

]