Grocery=[

"bakery",
"bakery samman",
"bread",
"bread rusk bun egg",
"chicken",

"chicken piece",
"chicken powder",
"chicken powder chat masala",
"chikn bread",
"coke",
"cold drink",
"cold drink refreshment",
"coldrink chip",
"daal",
"daal chawal cheni",
"dahi egg",
"daily gost sabzi",
"doodhwala",
"egg",
"egg bread",
"egg dahi slice",
"fish",
"fish meat",
"fish vegetable",
"forut sabzi",
"frout sabzi",
"fruit",
"fruit n vegetable",
"fruit n vegitables",
"fruit nd chicken",
"fruit sabzi",
"fruit sbze",
"fruit snack",
"fruit vagetables",
"fruit veg",
"fruit veges",
"fruit veges meat",
"fruit vegetable",
"fruit vegetable misc",
"fruit veggie",
"fruit veggie dry fruit",
"fruit vegi",
"fruit vegis",
"fruit vegitables",
"fruit vegitablr",
"fruite",
"makan",
"maryam sabzi",
"meat",
"meat chicken",

"milk curd",
"milk curt",
"milk dehi",
"milk dhahi",
"milkman",
"milkman monthly",
"nagori milk",
"rashan",
"refreshment",
"sabzi fruit",
"sabzi ghost",
"snack",
"snack biscuit chanachur",
"snack ice cream juice",
"snack juice",
"snack meal",
"snack n drink",
"soda salaf grocery home",
"tea cold",
"tea coldrink",
"tea milk",
"tea n milk",
"veg fish fruit",
"veg fruit",
"veg fruit meat",
"veg fruite meet",
"vegetable masal tomator lasun"

]
