


Grocery=["aali pyaz sabzi wagara",
"afghan bakery",
"aftar fruit",
"andy bread",
"aumber grocery",
"ayan bakery",
"ayra milk pampers wipe",
"baby milk",
"bakery",
"bakery breakfast",
"bakery dairy",
"bakery egg",
"bakery expense",
"bakery item",
"bakery samman",
"bf milk",
"bhawana home grocery fruit",
"bill gas mobile milk",
"bill milk",
"biscuit",
"bread",
"bread bakery",
"bread biscuit",
"bread butter",
"bread canteen",
"bread egg",
"bread egg butter",
"bread n snack",
"bread rooti",
"bread roti",
"bread rusk bun egg",
"bread wastage",
"break fast dairy milk",
"brown bread",
"buy milk",
"category",
"catering grocery",
"chicken",
"chicken beaf",
"chicken beed",
"chicken beef",
"chicken bill",
"chicken burger",
"chicken chilly",
"chicken egg",
"chicken egg mutton",
"chicken exp",
"chicken feed",
"chicken ghosht",
"chicken gosht",
"chicken haleem piyaz fry",
"chicken home",
"chicken kabab",
"chicken kebab",
"chicken meat",
"chicken meet",
"chicken monthly",
"chicken motan",
"chicken nihari",
"chicken paties",
"chicken patty",
"chicken payment",
"chicken piece",
"chicken powder",
"chicken powder chat masala",
"chicken roll",
"chicken run bar",
"chicken salami",
"chicken saruf",
"chicken soup",
"chicken wala",
"chikan maal",
"chiken mutton beaf",
"chiken patessz kns",
"chikn",
"chikn bread",
"child grocery",
"child milk",
"coffee coffee milk suger",
"coke",
"cold drink",
"cold drink refreshment",
"coldrink chip",
"daal",
"daal chawal cheni",
"daalian",
"daals",
"dahi egg",
"daily exp",
"daily expense",
"daily food",
"daily gost sabzi",
"daily grocery",
"daily house milk",
"daily living",
"daily meal",
"daily milk",
"daily petty expense",
"daily sabzi",
"daily veggie",
"dairy",
"dairy bakery",
"doodhwala",
"drink",
"drink cold drink",
"drink snack vend",
"drinking",
"dry fruit",
"eat fruit milk",
"eatable",
"egg",
"egg bread",
"egg bread butter",
"egg bread yogurt",
"egg dahi slice",
"egg fish",
"egg milk",
"egg monthly",
"egg n dahi",
"egg purchase",
"even snack",
"factory tea water snack",
"fish",
"fish meat",
"fish vegetable",
"food",
"food beverage",
"food fruit",
"food fruit veg",
"food vegetable",
"forut sabzi",
"fresh milk",
"fresh veg meat",
"frout sabzi",
"fruit",
"fruit adeel",
"fruit bkry item",
"fruit cereal",
"fruit exp",
"fruit f",
"fruit food item",
"fruit healthy diet",
"fruit home",
"fruit milk",
"fruit n diet",
"fruit n vegetable",
"fruit n vegitables",
"fruit nd chicken",
"fruit sabzi",
"fruit sbze",
"fruit snack",
"fruit vagetables",
"fruit veg",
"fruit veges",
"fruit veges meat",
"fruit vegetable",
"fruit vegetable misc",
"fruit veggie",
"fruit veggie dry fruit",
"fruit vegi",
"fruit vegis",
"fruit vegitable exp",
"fruit vegitables",
"fruit vegitablr",
"fruite",
"fruite meat",
"fruites sabzi",
"grocery",
"grocery baby care",
"grocery bakery",
"grocery beverage",
"grocery cash",
"grocery commodity",
"grocery confectionery",
"grocery confectionerygrocery confectionery",
"grocery daily",
"grocery dairry",
"grocery dairy",
"grocery food",
"grocery food non food",
"grocery fruit",
"grocery fruit vegetable",
"grocery general",
"grocery green",
"grocery home",
"grocery home exp",
"grocery honey",
"grocery hostel",
"grocery house hold",
"grocery household",
"grocery household return",
"grocery jumbo",
"grocery kid",
"grocery kitchen",
"grocery kitchen consumeables",
"grocery laundry",
"grocery meat",
"grocery milk",
"grocery milk breakfast",
"grocery mon qurbani",
"grocery monthly",
"grocery murree",
"grocery naqd",
"grocery personal",
"grocery pindi",
"grocery rice oil dal milk egg tea",
"grocery self",
"grocery self contribute",
"grocery snack",
"grocery soda",
"grocery soe soe",
"grocery store",
"grocery sunday market bill",
"grocery uniform",
"grocery utility eatab",
"grocery veg snack",
"grocery vegetable",
"grocery vegetable others",
"hareem milk",
"health fruit",
"home grocery",
"home grocery others",
"home meat vegitables",
"home milk",
"home vegetable",
"household grocery",
"icecream cold drink",
"juice",
"juice cold beverage",
"juice fruit veg",
" sabzi",
"khattak g store grocery",
"kid bakery",
"kid milk",
"kid milk buscuit",
"kid milk toiletry",
"kitchen",
"kitchen grocery",
"kitchen item vegetable",
"makan",
"maryam sabzi",
"meat",
"meat chicken",
"meat cock broiler beef",
"meat festiv",
"meat fish chic mutt",
"meat fish egg",
"meat fruit",
"meat fruit vegetable",
"meat mince",
"meat n chicken",
"meat product",
"meat vegetable",
"meat vegi",
"meat vegitablz",
"mechanic fruit",
"milk",
"milk advance",
"milk bakery",
"milk bf",
"milk bill",
"milk breakfast",
"milk cake chip",
"milk cash shop",
"milk curd",
"milk curt",
"milk dahi",
"milk daily",
"milk dairy",
"milk dehi",
"milk dhahi",
"milk eday",
"milk egg",
"milk exp",
"milk expense",
"milk fresh",
"milk home",
"milk",
"milk man",
"milk n yogurt",
"milk other dairy",
"milk pampers",
"milk sale",
"milk shake",
"milk shop",
"milk tea",
"milk wala",
"milk yasir",
"milk yogart",
"milk yogurt",
"milk yougart",
"milk youget",
"milk yougurt",
"milkman",
"milkman monthly",
"monthly grocery",
"moshur daal",
"myra grocery",
"nagori milk",
"ncb grocery",
"office grocery",
"office snack",
"oil",
"oil dal patti sugar grocery",
"orgeno milk",
"pamper milk j chp",
"pampers milk",
"pani cold drink",
"pindi home grocery",
"ramzan fruit",
"randomeat",
"rashan",
"refreshment",
"roti",
"sabi n fruit",
"sabzi",
"sabzi chicken",
"sabzi fruit",
"sabzi ghost",
"sabzi gosht dah",
"sabzi mandi meet",
"sabzi wagaira",
"sale egg",
"seperate grocery",
"snack",
"snack biscuit chanachur",
"snack chip",
"snack drink",
"snack fruit",
"snack ice cream juice",
"snack juice",
"snack meal",
"snack n drink",
"snack namaste",
"snack noodle dabli chhola biscuit",
"snack office",
"snack sweet",
"soda salaf grocery home",
"tea cold",
"tea coldrink",
"tea milk",
"tea n milk",
"veg fish fruit",
"veg fruit",
"veg fruit meat",
"veg fruite meet",
"veg n meat",
"vege fruit",
"vege meat",
"vegetable",
"vegetable bill",
"vegetable fish",
"vegetable fish chicken",
"vegetable food",
"vegetable fruit",
"vegetable furit",
"vegetable home",
"vegetable item",
"vegetable masal tomator lasun",
"vegetable meat",
"vegetable n fruit",
"veggie",
"vegitable",
"vegitable fruit",
"vegitables milk",
"water",
"weekly grocery",
"zaynab milk",
"zimre grocery",
"zunair milk others",
]

