Grocery={

"Meat":(
"meat",
"chickem",
"chiken",   
"mutton",
"muton",
"beef",
"fish",
"mince meat",
"red meat",
"poultry",
"meat & poultry",
"fish & meat",
"ghosht",
"ghost",
"gosht",
"murgi",
"bakra",
"prwan",
"prawns"
),


"Fruits & Vegetables":(
    "fruit",
    "apple",
    "banana",
    "orange",
    "apricot",
    "avacado",
    "grapefruit",
    "grapes",
    "guava",
    "lychee",
    "lichi",
    "pineapple",
    "pomegranate",
    "watermelon",
    "rasberries",
    "fruit",
    "fruite",
    "fruites",
    "froot",
    "frot",
    "aloo",
    "piyaaz",
    "piyaz",
    "temator",
    "timatar",
    "tomato",
    "potato",
    "gobi",
    "palak",
    "dhania",
    "podina",
    "lehsun",
    "adrak",
    "mooli",
    "bhindi",
    "gajar",
    "loki",
    "onions",
    "garlic",
    "potatos",
    "reddish",
    "carrot",
    "cabbage",
    "cauliflower",
    "broccoli",
    "lettuce",
    "ginger",
    "pumpkin",
    "tomatoes"
    "cucumber",
    "veg",
    "veggie",
    "vegs",
    "vegitable",
    "vegetable",
    "vegettable",
    "vegetabel",
    "vagetabel",
    "phal",
    "phall",
    "sabzi",
    "sbzi",
    "sabzii",
    "sabzy",
    "aloo",
    "peyaz",
    "sabze",
    "dates",
    "dryfruit",
    
),

"Dairy Products":(
    "milk",
    "doodh",
    "butter"
    "makhan",
    "egg",
    "eggs",
    "cream",
    "yougat",
    "yogurt",
    "yoghurt",
    "curd",
    "dahi",
    "curt",
    "dehi",
    "curd",
    "bread",
    "cheese",
    "double roti",
    "everyday",
    "noorpur butter",
    "nurpur butter",
    "icecream",
    "olpers",
    "dayfresh",
    "milkpak",
    "haleeb",
    "tarang",
    "nesvita",
    "nido",
    "cerelac",
    "enfamil",
    "pediasure",
    "kulfi",
    "malai",
    "dahi",
    "rabri",
    "rasmalai",
    "custard",
    "pudding",
    "ice cream",
    "cake",
    "chocolate",
    "desserts",
),
    "Pantry":(
        "rashan",
        "pantry",
        "flour",
        "maida",
        "patti",
        "coffee",
        "sugar",
        "cheeni",
        "aata",
        "chaawal",
        "jelly",
        "brown rice",
        "rice",
        "chawal",
        "macaroni",
        "macroni",
        "ketchup",
        "chili sauce",
        "chilli sauce",
        "soy sauce",
        "spaghetti",
        "spageti",
        "noodle",
        "noodles",
        "maggi",
        "noodel",
        "daal",
        "daleya",


    ),
"Spices":
    (   "spices",
         "oil",
        "cooking oil",
       "soya supreme"
        "tail",
         "tel",
        "masala",
        "vinegar",
        "cocoa",
        "vanila"
    ),
"Snacks":(
    "biscuits",
    "chocolate",
    "chips",
    "biscut",
    "cocomo",
    "cheez",
    "lays",
    "cookies",
    "bun",
    "bakery"
    "nuggets"
    "kitkat",
    "waffers",
    "rusk",
    "cupcakes",
    "fries",
    "nutella",
    "cereal",
    "milo",
    "cold drinks",
    "pepsi",
    "7up",
    "mirinda",
    "coke",
    "soft drinks",
    "sting"
)
    "Cosmetics":(
        "soap",
        "sabun",
        "facewash",
        "toothpaste",
        "toothbrush",
        "brush",
        "shampoo",
        "shampo",
        "bodyspray",
        "perfume",
        "prfume",
        "razor",
        "blade",
        "shave",
        "gillette",
        "parfume",
        "conditioner"

    ),
    "Miscellaneous":("soda sarf",
                     "sauda",
                     "grossery",
                     "grcy",
                     "groceri",
                     "gocery",
                     "surf",
                     "sarf",
                     "washing powder",
                     "ariel",
                     "lemon max",
                     "bar soap",
                     "surf exel",
                     "powder",
                     "katchup",
                     "mayonnaise",
                     "drinking water",
                     "sauces",
                     "chilly powder",
                     "fenia",
                     "jhaaroo",
                     "dishwash liquid",
                     "scrub",
                     "spray",
                     "pampers",
                     "tissues",
                     "napkins",
                     "rose petal"

                     )



}

