Installments={
"Installments":(
"installment",
"installments",
"car installment",
"bike installment",
"loan installment",
"mobile installment",
"plot installment",
"bank Installment",
"fridge installment",
"vehicle Installment",
"Home Decor Car Installment",

"AC Installment",
"Ac installment",

"TV Installment",
"investment for installment account",
"Committee car installment",
"Washing Machine Installment",
"Akhuwat Installment ",
"Credit Card Installment",
"Flat Installment",
" installment ",
"Shop installment",

"CBRECHS Installment",
"Gulshan e Bahaar plot installment",

"Faraz bhai mobile installment",
"Home Installment",


"Car Installments ",
"Fan Installment ",

"Installment 1",
"Installment 5672",
"Installment car",
"Installment house",
"Led installment",
"Mobile installment ",
"Monthly Installments",
"Refrigerator Installment",

"car installment",
"Bills n installments",
"Monthly Installment",
"Installment Office ",
"Bank Installments",
"Bank installment and credit card",
"Installment Balance Income",
"Monthly Installment ",
"Central park installment ",
"AC Installments ",
"Monthly installment",
"City Loan Installment",
"LED Installment",
"Loan Payed Installment ",
"Bank installments",
"Car loan installment",
"Hi roof installments",
"Installment Askari Bank",
"Land Installment",
"SC Installment",
"UPS-Installment",
"Wadi Degla Club Installment",
"6775 installment",
"Baik Installment ",
"Bank Personal Loan Installment",
"Car Loan Installment ",
"Committee & installment",
"Garage Installment",
"Installment Mobile ",
"Installment Shaz",
"Owais Mobile installment",
"Phoneinstallment",
"A c installment",
"Altis Installment",
"BAHL Installment ",
"Bank Installments NIB",
"Bus installment",
"Bwc.installment",
"Fixed Installments",
"Gawadar installment ",
"Honor 7 Installment ",
"Installment Loan",
"Installment Loupes and Light",
"Installment Payment",
"Installment Shop Fahad",
"Installment lhr",
"Installments Badya",
"Installments phone",
"Investments/Installments",
"Laptop Installment",
"Meezan installment # 10,11",
"Mobile Installment Plan",
"Surmawala installments",
"Ac Installment",
"Apartment Installments",
"BC Installment",
"Bank alfalah installment plan",
"Bank loan installment",
"Bike installments",
"By cycle Installment",
"Commitee installment",
"Commitee installment wise",
"Committee & Bike Installments ",
"Committee Installment",
"Credit card installment",
"DHA installment",
"Fee Installment For Fall-18",
"Flat Installments",
"Fsysal Installment",
"House Loan Installment",
"Ijara Installment",
"Installment Plans",
"Installment Speaker",
"Installment bc",
"Installment of plot ",
"Karachi 1000Sq Installment",
"LIC Installment",
"LMC Installment",
"Loan/Installment",
"MOBILE INSTALLMENT",
"Meezan installment #8,9",
"Mian Jee Installment ",
"Monthly installments ",
"Nova 3i Installments ",
"Omega Installment",
"Ownership Right installment",
"Refrigrator Installment",
"Submit installment Awais Khaleel",
"Surjani Villas Installments",
"Tv installment",
"Tyre installment",
"Varsity installment",
"Vc installment 50000",
"Vc installment 70000",
"Vehicle Installment ",
"hiroof  installment ",
"phone Installment. ",
"3rd Installment ",
"4th Installment ",
"A/C Installment",
"AC Installments",
"AC installment",
"AC installment ",
"ASF Installments ",
"Ac Installment ",
"Askari Installment",
"Askari Loan installment",
"Auto Loan Installment",
"Awaz Agahi Center Installment ",
"BC-Installment",
"BISIC INSTALLMENT ",
"BRACK INSTALLMENT ",
"Bajaj installment ",
"Bank Installments ",
"Bank Loan Installment ",
"Bank load installment",
"Bank loan Installment",
"Bike + AC installment",
"Bike Installments ",
"Bike and car installment ",
"Bike installment ",
"Bike ki Installment",
"Bilal Installment",
"Byce installment",
"Byic Installment",

"CSD installment",

"Car Lease Installment ",

"Carry Installment",
"Carry daba installment",
"Cell phone Installment ",
"Conte installment",
"Corolla installment",
"Credit card installments",
"Csd installment",
"Cultus Installment",
"DHA Plot Installment",
"DPS Installment",
"Debt Installment",
"Dha installment",
"Electronic installment ",
"Electronics Installments",
"Every Van installment",
"FAYSAL BANK INSTALLMENT",
"Fans installment",
"Faraz and tariq bhai installment",
"Fee installment#1",
"Fridge Installment",
"Fridge installment ",
"Fridge's Installment",
"Gari ki Installment",
"Geaser installment",
"HBL Installment",
"HBL Loan Installment",
"HUAWEI Installment ",
"Haier Installment",
"Home loan installment ",
"House Construction installment ",
"House Installments",
"House loan installment",
"INSTALLMENT",
"INSTALLMENT PAID TO MAMA",
"IPS Installment",
"Installment 2",
"Installment 5675",
"Installment AC",
"Installment Bike Mobile ",
"Installment Inverter",
"Installment LED",
"Installment Mobile",
"Installment Motor Cycle",
"Installment Of Car",
"Installment Of Cell phone ",
"Installment Of the Shop ",
"Installment Plot",
"Installment Sensor ",
"Installment aks",
"Installment dryer",
"Installment for House",
"Installment for bike",
"Installment led",
"Installment mobile",
"Installment of car",
"Installment of khairpur plot",
"Installment of mom",
"Installment plot",
"Installment to bhaijan",
"Installment(Fridge)",
"Installments Afzal Electronics ",
"Installments Car",
"Installments for DHA",
"Insurance Installments",
"Ist Installment ",
"Jenah town plot installment",
"Kashaf Installment",
"Khalid Mamoo Installments",
"Khan installment",
"Kista (Installment)",
"LED On Installments",
"Land installments",
"Lcd installment",
"Led Installment",
"Led Installment ",
"Loan Installment EBL",
"Loan Installment Plan",
"Loan Installments ",
"Loan MCB Installment",
"Loan installment ",
"Lottery Installment",
"M.Pt Installment",
"Meezan installment",
"Meezan installment # 12,13",
"Mehran installment",
"Mobile bike installment",
"Mobole Installment",
"Moile installment",
"Monthly Somity Installment",
"Monthly cash installment ",
"Monthly installment ",
"Monthly installments",
"Motercycle installment",
"Motorcycle Installment",
"Motorcycle installment ",
"NGO Installment",
"NSB installment",
"Nabil Installment",
"Nrsp Installment ",
"Other Installment ",
"PCJ INSTALLMENT ",
"PS4 Installment",
"Pelling installment rent",
"Personal Loan Installment ",
"Personal loan installment",
"Phone installment close",
"Plot Installments ",
"Plot installments ",
"Plot1 installment",
"Plot2 installment",
"Prider installments",
"Property Installment",
"Property installment",
"Qist installment",
"RD installment",
"RE installment",
"RUBA INSTALLMENT",
"Rafay installment",
"Real Estate Installments",
"Rupali installment",
"SCB (INSTALLMENT)",
"Scb installments",
"Scooty installment",
"Shop Installment",
"Siddhartha Installment ",
"Silk bank pl installment",
"Singer Installment",
"Sofa Installment",
"Talha car installment",
"Transfer SC Installment ",
"Tv Installment",
"Ubl last installment",
"University Fee Installment ",
"Ups installment",
"Van installment",
"Waleed bhai and Bike Installment",
"Weekly installment ",
"Yearly Installment Property ",
"car installments",
"dhu installment",
"installment bike",
"installment of led and phone",
"installment swift",
"installmentd",
"loan Installment",
"motercycle installment",
"surmawala  installment ",
"ubl last installment",
"EMI",
"Emi",
"Loan EMI",
"Car EMI",
"Mobile EMI",
"Bike EMI",
"Car Emi",
"Phone EMI",
"Car emi",
"Loan Emi",
"EMI ",
"Loan emi",
"Mobile emi",
"EMIs",
"Vivek bhia emi",
"Bank EMI",
"EMI LAND",
"EMI Loan",
"Home EMI",
"Home Loan EMI",
"House EMI",
"Loan & emi",
"AC EMI",
"Bike emi",
"Bullet EMI",
"CAR EMI",
"Car Loan Emi",
"Emi ",
"Mobile emi ",
"Tv EMI",
"EMI-loan",
"PL EMI",
"EMI/Loan",
"EMI & LOAN",
"EMI HL CAR",
"EMI payments [Loan+DPS+Shamity]",
"EMI & Card",
"EMI and Bills",
"Emi Smart 1",
"EMI global",
"EMI(laptop)",
"EmI",
"Loans /Emi",
"Other EMI",
"Tv Emi",
"Tvs scooty emi",
"6047 EMI",
"Bike Emi",
"Camera emi",
"CitiBank EMI",
"Credit Card Emi",
"EMI (laptop) ",
"EMI Bullet",
"EMI Kaimaathu",
"EMI Mobile",
"EMI and Credit card bills",
"EMI payment",
"EMI's",
"EMI-LOAN",
"Emi Amazon ",
"Hdfc Emi",
"Home loan Emi",
"Laptop emi",
"Activa EMI",
"Auto loan EMI",
"BMW EMI",
"BOI EMI",
"Bajaj emi",
"Bank emi",
"Bank(emi)",
"Bhaiyu mobile EMI",
"CC EMI",
"CITYbank EMI",
"CREDIT CARD EMI",
"Car Loan EMI",
"Credit Card + EMI",
"Credit Card EMI",
"Credit card emi",
"EMI Car",
"EMI Fridge",
"EMI HSBC",
"EMI Harley Davidson",
"EMI TO ROSHAN",
"EMI bike",
"EMI for Laptop",
"EMI home loan",
"EMI of Cultus",
"EMI phone",
"EMI to dad",
"Ecosport EMI",
"Emi  capital first",
"Emi Smart 2",
"Emi Smart Interest ",
"Emi and interest ",
"Emi car",
"Emi driver",
"Emi homecredit",
"Emi of bike",
"Emi of loan",
"Emi personel loan",
"Emi rajamama",
"Flat EMI",
"Flipkart EMI",
"Fridge EMI",
"Fridge emi",
"HDFC EMI",
"HL EMI",
"HL Emi",
"Honor 8x EMI",
"House Loan EMI",
"Indiabulls Loan EMI",
"Kolors EMI",
"LOAN EMI",
"Laptop EMI",
"Lets EMI",
"Loan EMI ",
"MMT EMI",
"MOBILE EMI",
"Mobile EMI ",
"Mobile EMI bill",
"Monthly EMI",
"Personal Loan EMI",
"Phone emi",
"Phone emi ",
"Redcarpet EMI",
"Sibin EMI",
"TV EMI",
"Tess Phone EMI",
"Vehicle EMI",
"car emi",
"emi",
"home emi"
 )
}
