Installments={
"Installments":(
 
"installment",
"installments",
"car installment",
"bike installment",
"loan installment",
"mobile installment",
"plot installment",
"bank installment",
"fridge installment",
"vehicle installment",
"home decor car installment",
"ac installment",
"tv installment",
"investment for installment account",
"committee car installment",
"washing machine installment",
"credit card installment",
"flat installment",
"shop installment",
"home installment",
"house installment",
"apartment installment",
"fan installment ",
"installment 1",
"installment car",
"installment house",
"led installment",
"monthly installments",
"refrigerator installment",
"bills n installments",
"installment office ",
"bank installments",
"bank installment and credit card",
"installment balance income",
"central park installment ",
"city loan installment",
"loan paid installment",
"car loan installment",
"hi roof installments",
"installment askari bank",
"land installment",
"sc installment",
"ups-installment",
"bank personal loan installment",
"car loan installment ",
"committee & installment",
"garage installment",
"phoneinstallment",
"a c installment",
"altis installment",
"bus installment",
"fixed installments",
"honor 7 installment ",
"installment loan",
"installment loupes and light",
"installment payment",
"installments phone",
"investments/installments",
"laptop installment",
"meezan installment # 10,11",
"mobile installment plan",
"surmawala installments",
"ac installment",
"apartment installments",
"bc installment",
"bank alfalah installment plan",
"bank loan installment",
"bike installments",
"by cycle installment",
"commitee installment",
"committee & bike installments ",
"dha installment",
"fee installment for fall-18",
"house loan installment",
"ijara installment",
"installment plans",
"installment bc",
"installment of plot ",
"loan/installment",
"mobile installment",
"mian jee installment ",
"monthly installments ",
"nova 3i installments ",
"omega installment",
"ownership right installment",
"tyre installment",
"varsity installment",
"vc installment 50000",
"3rd installment ",
"4th installment ",
"askari installment",
"auto loan installment",
"bc installment",
"bank loan installment ",
"bike + ac installment",
"bike installments ",
"bike and car installment ",
"bike installment ",
"byce installment",
"byic installment",
"car lease installment ",
"carry installment",
"cell phone installment ",
"conte installment",
"corolla installment",
"credit card installments",
"cultus installment",
"debt installment",
"dha installment",
"electronic installment ",
"every van installment",
"fee installment#1",
"gari ki installment",
"geaser installment",
"hbl installment",
"huawei installment ",
"haier installment",
"home loan installment ",
"house construction installment ",
"house installments",
"house loan installment",
"installment paid to mama",
"ips installment",
"installment 2",
"installment ac",
"installment bike mobile ",
"installment inverter",
"installment led",
"installment mobile",
"installment motor cycle",
"installment of car",
"installment of cell phone ",
"installment of the shop ",
"installment plot",
"installment dryer",
"installment for house",
"installment for bike",
"installment led",
"installment mobile",
"qist",
 "kist",
 "kistein",
"installment of mom",
"installment to bhaijan",
"installment(fridge)",
"installments car",
"installments for dha",
"insurance installments",
"1st installment ",
"kista (installment)",
"land installments",
"lcd installment",
"loan installment plan",
"lottery installment",
"meezan installment",
"mehran installment",
"mobile bike installment",
"mobole installment",
"monthly cash installment ",
"motercycle installment",
"ngo installment",
"other installment ",
"ps4 installment",
"personal loan installment",
"property installment",
"qist installment",
"real estate installments",
"scooty installment",
"sofa installment",
"transfer installment ",
"university fee installment ",
"ups installment",
"van installment",
"weekly installment ",
"yearly installment property ",
"installment bike",
"installment of led and phone",
"installment swift",
"motercycle installment",
"last installment"
),
 
 "EMI" :(
"emi loan",
"ac emi",
"emi harley davidson",
"emi and bills",
"emi for laptop",
"hdfc emi",
"house emi",
"emi  capital first",
"emi bike",
"bullet emi",
"home loan emi",
"emi and interest ",
"house loan emi",
"personal loan emi",
"phone emi ",
"credit card emi",
"emi of bike",
"tvs scooty emi",
"honor 8x emi",
"emi & card",
"loan emi",
"emi fridge",
"loan emi ",
"fridge emi",
"citybank emi",
"laptop emi",
"emi amazon ",
"credit card + emi",
"emi smart interest ",
"tv emi",
"citibank emi",
"emi and credit card bills",
"emi land",
"vehicle emi",
"bank(emi)",
"emi",
"emi payment",
"pl emi",
"emi(laptop)",
"flipkart emi",
"bike emi",
"emi homecredit",
"emi car",
"emi/loan",
"emi payments",
"camera emi",
"bmw emi",
"auto loan emi",
"car emi",
"phone emi",
"mobile emi",
"emi to dad",
"monthly emi",
"flat emi",
"emi global",
"emi ",
"bank emi",
"car loan emi",
"emi home loan",
"emi hsbc",
"emi & loan",
"emi (laptop) ",
"emi driver",
"emi personel loan",
"emi of loan",
"emi mobile",
"other emi",
"loans /emi",
"emi phone",
"home emi",
"mobile emi bill",
"emi of cultus",
"mobile emi "
  
 )
}
