Mobile_Expenses=["mobile Expenses",
                 "mobile",
"balance mobile",
"mobile",
"cell phone",
"easy load mobile card",
"easyload",
"fone recharge",
"internet cell",
"mobile allownce",
"mobile balanace",
"mobile",
"mobile call",
"mobile cover",
"jazz",
"iphone",
"samsung",
"nokia"
"xiaomi"
"blackberry"
"mobile due samsung",
"mobile internet",
"mobile phone",
"mobile phone balance",
"mobile pkg",
"mobile repair",
"omni mobile account",
"personal mobile",
"phone",
"phone accessory",
"phone balance",
"phone card",
"phone charge",
"phone expense",
"recharge",
"recharge card",
"telephone data",
"telephone internet",
"utility mobile",

]