Office_Expense = {
"Office_Expence":(
"office",
"office launch",
"office assets",
"office expenses - stars",
"office & my expanses",
"office fund",
"jers office sitr",
"fariha office expenses",
"expense office",
"office eatries",
"office mess",
"office saman",
"office petty",
"office coffee",
"worker salary",
"office expanse",
"office all",
"office colleague etx",
"office use",
"office  outfall",
"office canteen",
"office work",
"office  garhi shahu",
"eat in office",
"office supplies",
"office material",
"in office",
"office returnables",
"head office load",
"office payable",
"office refreshment",
"office parking",
"office wali",
"pay to workers",
"office expence",
"office outfall",
"office purchase",
"office etc",
"office exp",
"office mobiles",
"office things",
"office expense",
"workshop kurcha",
"work",
"stock work",
"office staff",
"office cost",
"work expenses",
"bdf officer's fund",
"office khaana",
"office meal",
"others cost (office)",
"my office",
"office cash",
"office stuff",
"office expenses",
"office others",
"office expences",
"head office expense",
"office conveyance",
"karaya office swl"
  )
}





