office_Expense=["Office_Expence","Office",
"Office ",
"Office expense",
"Office Expense",
"Office Expenses",
"Office expenses",
"Office Exp",
"office",
"Office Expenses ",
"Office Cash",
"Office exp",
"Office expenses ",

"OFFICE",
"office ",
"Office Use",
"Office expense ",
"Office expanse ",
"Office Saman",
"Office Mess",
"Office Work",
"Office Supplies",
"Office expence",
"Office staff ",
"BDF Officer's Fund",
"office expence",
"office exp",
"Office Material",
"Office Expanse",
"Head Office Load",
"Office colleague etx",
"Office work",
"Office Expence",
"Office others",
"Office Stuff",
"Office fund",
"Office petty",
"Office use",
"Office Purchase",
"Office Canteen",
"Office all",

"Office meal",
"Office mobiles",
"JERS Office sitr",
"Expense office ",
"OFFICE EXP",
"Office cost ",
"Office Expences",
"Office  Garhi Shahu",
" Office Parking",
"Office  Outfall",
"In Office",
"Fariha Office Expenses",
"Head Office Expense",
"Office eatries",
"Office Conveyance",
"Office & My Expanses ",
"Others cost (office)",
"Office Expenses - Stars",
"Office Launch",
" Office",
"Office payable",
"Office Coffee",
"Office",
"Karaya Office Swl",
"Office things",
"Office Refreshment",
"Office Outfall ",
"Office Meal ",
" office",
"Office Expense ",
"Office etc",
"Eat in Office",
"My Office",
"Office ",
"Office   ",
"Office Returnables",
"Office wali",
"office expenses ",
"Office Assets ",
"Office Khaana","Work expenses ",

"Workshop kurcha",
"  Work ",

"Stock work",
"Worker salary ",
"Pay To Workers",

]