Rent={
    
"Rent":(
    
"karaya",
"keraya",
"rent",
"rant",
"kiraya",
"keraia",
"rental",
"rentol",
"renting",
"rented",
 "rents",
    "rent payable",
    "give rent",
    "get rent",
    "rent given",
    "rent paid",
    "rent payment",
    "rent taken",
    "rent received",
    "monthly rent",
    "rent income",
    "advance rent",
   
 
),

    "House":(
              "house rent",
              "ghar rent",
              "makaan rent",
              "makan rent",
              "flat rent",
              "flate rent",
              "appartment rent",
              "room rent",
              "kamray rent",
               "kamra rent",
              "home rent",
               "hostel rent",
               "quater rent",
                "quarter rent",
                "plot rent",
                "floor rent",
               "portion rent",
               "quator rent",
               "quatr rent",
                "residence rent"
              ),

"Vehicle":(
            "car rent",
            "rent a car",
           "bike rent",
           "uber rent",
           "careem rent",
           "riksha rent",
           "rickshaw rent",
           "auto rent",
           "ricksha rent",
           "gari rent",
           "gaari rent",
           "suzuki rent",
           "cargo rent",
           "vigo rent",
           "vehical rent",
           "vehecal rent",
           "tempo rent",
           "bus rent",
           "jeep rent",
            "mazda rent",
           "truck rent",
           "taxi rent",
            "van rent",
            "transit rent",
            "transport rent",
            "vehicle rent",
           ),


"Business Rent":("office rent",
                 "shop rent",
                 "dokan rent",
                 "karobar rent",
                 "dukaan rent",
                 "dukan rent",
                 "factory rent",
                 "clinic rent",
                 "academy rent",
                 "building rent",
                 "property rent",
                 "stall rent",
                 "salon rent",
                 "karkhana rent",
                 "goddam rent",
                 "godown rent",
                 "warehouse rent",
                 "plaza rent",
                 "store rent",
                 "zameen rent"

                 ),


"miscelaneous rent":("garage rent",
                      "giraj rent",
                      "garagge rent",
                      "market rent",
                      "markeet rent",
                      "furniture rent",
                      "hall rent",
                      "parking rent",
                      "coaching rent",
                      "agricultural rent",
                      "loader rent",
                      "hotel rent",
                      "pg rent",
                      "hostel rent",
                      "hotel rent",
                      "restaurant rent",
                     "coaching rent",
                     "center rent",
                     "tuition rent",
                      "security rent",
                      "mobile rent",
                      "locker rent",
                       "travel rent",
                     "tools rent"
               )
}
