Shopping=["Shopping",
"cloth",
"cloth assesories",
"clothe",
"clothes",
"clothes shoe",
"shopping",          
"clothing",
"cut shoe polish",
"dress",
"dress cloth",
"dress press",
"dress shoe",
"dress shopping",
"eid shopping",
"family shopping",
"marriage shopping",
"marriage shopping arsal",
"shadi shopping",
"shoe",
"shoe cloth",
"shoe makeup",
"shoe polish",,
"shopping",
"shoping",
"shooping",          
"wedding clothes",
]


