Shopping={
    
    "Shopping":("shopping",
                "shoping",
                "shooping",
                "karedari",
                "bazaar",
                "bazar"
                "online shopping",
                "khareedari",
                "winter clothes",
                "shaadi shopping",
                "bari shopping",
                "jahez shopping"
                ),
    
    "Brands":(
                    "levis",
                    "levi's",
                    "denizen",
                    "gul ahmed",
                    "gulahmed",
                    "zellbury",
                    "zelbury",
                    "stoneage",
                    "stone age",
                    "khaadi",
                    "kaadi",
                    "csd",       
                    "khadi",
                    "sana safinaz",
                    "firdoz",
                    "dinners",
                    "fifth avenue",
                    "dockers",
                    "sensation",
                    "sentsation",
                    "outfitters",
                    "out fitters",
                    "junaid jamshed",
                    "j.",
                    "alkaram",
                    "chenone",
                    "hushpuppies",
                    "rolex",
                    "nike",
                    "addidas",
                    "upper",
                    "hoodie",
                    "jaffer jees",
                    "jafferjees",
                    "hsy studio",
                    "edenrobe",
                    "warda"
                    ),

"Clothing":("cloth",
            "kapray",
            "coat",
            "pant",
            "shirt",
            "tie",
            "kurta",
            "kurti",
            "shalwar kameez",
            "lawn",
            "silk",
            "khaddar",
            "kapra",
            "trousers",
            "dress",
            "shorts",
            "kameez",
            "unstiched",
            "saree",
            "tshirt",
            "t-shirt",
            "t shirt",
            "socks",
            "sleves",
            "suit",
            "sweater",
            "sweter",
            "hi neck",
            "blazer",
            "jacket",
            "overalls",
            "pyjamas",
            "jeans",
            

           ),

"Accessories":(
              "watch",
              "clock",
              "cufflings",
              "cufling",
              "cufflinks",
              "tie pin",
              "ring",
              "jewellry",
              "jewellery",
              "jewlery",
              "necklace",
              "ring",
              "bracelate",
              "bracelet",
              "churiyan",
              "churiyyan",
              "ear rings",
              "earrings", 
              "wallet",
              "purse",
              "hand bag",
              "clutch",
               

              ),


"Shoes":("shoe",
         "shoes",
         "sneakers",
         "snickers",
         "formal shoes",
         "casual shoes",
         "dress shoes",
         "sandals",
         "kolahapuri",
         "mojri",
         "khussay",
         "chappal",
         "chapal",
         "heels",
         "jootay",
         "joggers",
         "jogers",
         "fancy shoes",
         "shadi shoes"
        )
    
}

