Shopping={
    
    "Shopping":("shopping",
                "shoping",
                "shooping",
                "karedari",
                "bazaar",
                "bazar"
                ),
    
    "Brands":("Levis",
                    "levi's",
                    "denizen",
                    "gul ahmed",
                    "gulahmed",
                    "zellbury",
                    "zelbury",
                    "stoneage",
                    "stone age",
                    "khaadi",
                    "kaadi",
                    "csd",       
                    "khadi",
                    "sana safinaz",
                    "firdoz",
                    "dinners",
                    "fifth avenue",
                    "dockers",
                    "sensation",
                    "sentsation",
                    "outfitters",
                    "out fitters",
                    "junaid jamshed",
                    "j.",
                    "Alkaram",
                    "jacket",
                    "pant",
                    "ChenOne",
                    "hushpuppies",
                    "rolex",
                    "nike",
                    "addidas",
                    "upper",
                    "hoodie",
                    "jaffer jees",
                    "jafferjees",
                    "HSY Studio",
                    "HSY Studio",
                    "edenrobe",
                    "warda"
                    ),

"Clothing":("cloth",
            "kapray",
            "coat",
            "pent",
            "shirt",
            "tie",
            "kurta",
            "kurti",
            "shalwar kameez",
            "online shopping",
            "trousers",
            "dress",
            "shorts",
            "kameez",
            "unstiched",
            "saree",
            "tshirt",
            "t-shirt",
            "t shirt",
            "socks",
            "sleves",
            "suit",
            "sweater",
            "sweter",
            "hi neck",
            "blazer"

           ),

"Accesaries":("watch",
              "clock",
              "cufflings",
              "cufling",
              "cufflinks"
              "tie pin",
              "jewellry",
              "jewellery",
              "jewllery",
              "neckles",
              "ring",
              "bracelate",
              "bracelet",
              "churiyan",
              "ear rings",
              "wallet",
              "purse"

              ),


"Shoes":("shoe",
         "snickers",
         "formal shoes",
         "dress shoes",
         "sandal",
         "kolahapuri",
         "chappal",
         "chapal",
         "jotay",
         "joggers",
         "jogers")
    
}

