Public_Transport=[
"autorickshaw",
"bus",
"bus conveyance",
"bus dpwn",
"bus fair",
"bus fare",
"bus free",
"bus taxi",
"bus taxi fare",
"bus ticket",
"bykea",
"bykea careem",
"cab",
"cab bus metro",
"cab fair",
"careem",
"careem business",
"careem captain",
"careem company",
"careem daily cash",
"careem driver",
"careem earnings",
"careem gross income",
"careem guarentee",
"careem return",
"careem ride",
"careem uber",
"careem weakly",
"careemuber",
"carem uber",
"cash collection today careem",
"cash collection today uber",
"chinchi",
"cost careem",
"cream uber rent",
"creem",
"creem earn",
"creem ride earn",
"daewoo bus",
"daily careem cash collection",
"daily earn uber",
"daily rent taxi",
"fair",
"fare",
"grab taxi",
"minicab",
"ola taxi",
"ola uber",
"rickshaw",
"rickshaw uber cng",
"ride careem",
"ride uber",
"rikshaw taxi",
"taxi",
"taxi fare",
"taxi rent",
"taxi rikshwa",
"taxify",
"ticket",
"toll bus ferry",
"ubar",
"uber",
"uber careem",
"uber careem earn",
"uber cash",
"uber cash collect",
"uber cash collection",
"uber cream",
"uber cream fair",
"uber creeam",
"uber creem",
"uber daily cash",
"uber drive",
"uber driver",
"uber earn",
"uber earn cash",
"uber eats",
"uber fare",
"uber lunch",
"uber nd careem",
"uber pathao fair",
"uber ride"]