Wedding=[
"Wedding",
"Wedding ",
"Weddings",
"Wedding Expenses",
"Wedding Attending",
"Wedding Expense",
"wedding money",
"Wedding decoration",
"Wedding Loan",
"wedding",
"For Others Wedding",
"Weddings Cash",
"weddings",
"Wedding shoot",
"Wedding Exp",
"Abdullah Wedding",
"Annys Wedding",
"Shazia Wedding",
"Wedding Expenses ",
"Wedding & Birthday ",
"Dai wedding ",
"Mehak wedding expenses",
"Madiha wedding",
"Raheela wedding exp",
"Weddings ",
"Wedding - Clothes ",
"Wedding Expanses",
"Maryam Wedding ",
"Wedding Decorations ",
"Weddings Expenses",
"Abid wedding",
"Wedding Trip",
"Wedding payment",
"Different Wedding expenses ",
"My Wedding",
"Samreen Wedding",
"Wedding shoping ",
"Aqsa wedding",
"Arooba Wedding ",
"Jia wedding shopping",
"Wedding Core",
"Wedding expense",
"Wedding expenses",
"Wedding shopping",
"Family Dinner/Lunch,gift/weddings",
"Family Wedding Gifts",
"For wedding",
"Loan for arsalan wedding",
"Wedding + valima",
"Wedding Days Expenses",
"wedding pkr",
"Ali's wedding",
"Ambreen wedding advance payment",
"Aqeel Wedding Salami",
"Arish Wedding",
"Aseer's Sister Wedding",
"Avni wedding",
"Awais ratyal's wedding ",
"Baqir's wedding",
"Bhai sahab wedding salami",
"Credit card bill of wedding shoping",
"Friends Wedding",
"Friends wedding ",
"Haani Wedding",
"Kashan sis wedding",
"Mustafa Wedding ",
"Nishat wedding last time walima",
"Rida's wedding ",
"Saira's wedding",
"Salsa's wedding",
"WEDDING ",
"Wedding Budget",
"Wedding Expense ",
"Wedding Fund",
"Wedding Moosa",
"Wedding Party",
"Wedding Photography",
"Wedding Salami",
"Wedding anniversary ",
"Wedding hall",
"Yasir Wedding ",
"Marriage",
"Marriage ",
"Marriage Expenses",
"Tayeba Marriage ",
"Marriages ",
"Marriage Expense ",
"Marriage ceremonies ",
"Marriages",
"Bilal Marriage",
"Arshad marriage ",
"Nehan Marriage Exp",
"Marriage Shopping",
"Nadeem marriage",
"Sister Marriage",
"MARRIAGE",
"Marriage - Functions - Events",
"Pikka Marriage",
"Marriage hal. expences.",
"Nehan Marriage Donation",
"Rony marriage",
"Clothing for marriage",
"Zamar Marriage expenses",
"Guests MARRIAGE ",
"Sonu marriage",
"Abrar Marriage",
"Brother's Marriage",
"Marriage Shopping Arsal",
"Marriage shopping",
"Shoping Marriage",
"Tayyaba's Marriage",
"Attending Marriage",
"Lend to kabbu for marriage",
"Marriage Cermony",
"Marriage Hisap",
"Marriage Loan ",
"Marriage expenses ",
"Marriage party expenses",
"Marriage personal shopping",
"Abr Marriage",
"Friend marriage ",
"Marriage Expenses ",
"Marriage Hall",
"Marriage Salami",
"Marriage ceremony ",
"Marriage function",
"Mehreen marriage",
"Salami Marriage",
"Wasif's marriage ",
"marriage expensive & powa",
"Ahmad mugal marriage",
"Aneesh sis marriage",
"Bro Marriage",
"Daima marriage ",
"Family Marriage",
"Fridge - Marriage ",
"Friend Marriage",
"Frnd marriage ",
"Hamerd Marriage",
"Incentive of marriage",
"Marriage  Expense ",
"Marriage Anniversary ",
"Marriage Ceremonies",
"Marriage Cover",
"Marriage Gift",
"Marriage Stuff",
"Marriage at family",
"Marriage c o Mahindra ..",
"Marriage cermony",
"Marriage chalo",
"Marriage clothes",
"Marriage clothes Sajjad ",
"Marriage expenses",
"Marriage expenses..band baja",
"Marriage gift",
"Marriage hall. ky kharchy. ",
"Marriage saman",
"Marriage shagun",
"Nafees marriage",
"Nasir's sis Marriage",
"Neeoandara 4 Marriage",
"Shehzad Marriage",
"Sikander Sis. Marriage",
"Zahid marriage",
"amber marriage",
"marriage",
"marriage gift",
"sari for marriage",
"Shaadi ",
"Shadi",
"Shaadi",
"Shadi Exp",
"Shadi shopping",
"Shadi ",
"Shaadi goar wagera",
"Shadi Expense",
"Shadi account",
"Shadi exp",
"Shadi card",
"shadi",
"Shadi gift",
"Shadi hall",
"Shaadi Tyari",
"Shaadi prep expenses",
"Nilu Shaadi",
"Shaadi Exp",
"Shaadi Expense ",
"Shaadi clothes",
"SHAADI",
"Shaadi nendr",
"shaadi food",
"Mithai shaadi",
"Shaadi Expenses",
"Shaadi Salami",
"Shaadi dresses",
"Shaadi ka kharcha",
"Shaadi kayliye petrol",
"shaadi",
"Adeel shadi",
"SHADI / B.DAY / GIFTS ETC",
"Ahsan Ki Shadi",
"Shadi Gift",
"Adi Shadi ",
"shadi mubra",
"Shadi expenses",
"Pindi Shadi",
"SHADI EXP",
"Shadi shoping",
"Shadi (bartan)",
"Shadi Ashoo",
"Shadi Expanses",
"Shadi Expenses",
"shadi kharcha",
"Adi shadi",
"Shadi & Shopping ",
"Shadi Hall",
"Shadi expense ",
"Baji ki shadi",
"Noman USA for shadi",
"Papa shadi",
"Shadi Biya",
"Shadi Mubarik",
"Shadi salamian",
"Shan Shadi",
"saba shadi",
"Amir Shadi",
"Amount Given on Shadi ",
"Mana shadi",
"Noman shadi",
"Saani shadi dress",
"Shadi Shopping ",
"Shadi expense",
"Shadian",
"main budget shadi",
"Advance shadi card",
"Ahmer Shadi ",
"Aimen ki shadi",
"Amir shadi",
"Asif Shadi Nyondra",
"Dawood shadi",
"Farhan bhai shadi",
"Fawad Shadi Lifafa",
"Ibrahim ki shadi",
"Kasur Shadi",
"Khadim shadi",
"Moavia Shadi",
"NaDeeM juTT ShaDi",
"Raheel shadi",
"Rana jabir shadi",
"SHADI EXPENSE",
"SHADI Salami",
"Shadi Account ",
"Shadi Biahh",
"Shadi Causon & Friend",
"Shadi Events Expence",
"Shadi Expence",
"Shadi Movie Pics",
"Shadi Payments",
"Shadi Salami",
"Shadi Shopping",
"Shadi expenses ",
"Shadi fees",
"Shadi m diye",
"Shadi movie",
"Shadi py act reciveabale",
"Shadi slaami",
"Shadi suit",
"Shadi sweettravelling ",
"Shadi vistro",
"Shadii",
"Shadii card",
"Shoping at azra shadi ",
"Tahir shadi",
"Waseem shadi",
"Zaid shadi",
"shadi bukan",
"zkwan shadi",
]