Wedding={
"Wedding":(
"wedding",
"wedding expenses",
"wedding attending",
"wedding loan",
"wedding - clothes ",
"wedding shoping ",
"wedding gifts",
"wedding budget",
"wedding expense ",
"wedding fund",
"wedding party",
"wedding photography",
"wedding salami",
"wedding anniversary ",
"wedding hall",
"marriage",
"marriage expenses",
"marriage ceremonies ",
"marriages",
"sister marriage",
"marriage - functions - events",
"marriage hal. expences.",
"nehan marriage donation",
"clothing for marriage",
"guests marriage ",
"brother's marriage",
"marriage shopping",
"shoping marriage",
"marriage cermony",
"marriage loan ",
"marriage expenses ",
"marriage party expenses",
"marriage personal shopping",
"marriage hall",
"marriage salami",
"marriage ceremony ",
"marriage function",
"marriage anniversary ",
"marriage ceremonies",
"marriage cover",
"marriage gift",
"marriage stuff",
"marriage clothes",
"marriage hall. ky kharchy. ",
"marriage saman",
"marriage shagun",
"marriage gift",
"sari for marriage",
"shadi",
"shadi exp",
"shadi shopping",
"shadi ",
"shaadi goar wagera",
"shadi expense",
"shadi account",
"shadi exp",
"shadi card",
"shadi",
"shadi gift",
"shadi hall",
"shaadi exp",
"shaadi expense ",
"shaadi clothes",
"shaadi food",
"mithai shaadi",
"shaadi expenses",
"shaadi salami",
"shaadi dresses",
"shaadi ka kharcha",
"shadi expanses",
"shadi kharcha",
"shadi & shopping ",
"shadi hall",
"amount given on shadi ",
"saani shadi dress",
"advance shadi card",
"fawad shadi lifafa",
"shadi salami",
"shadi account ",
"shadi biahh",
"shadi events expence",
"shadi expence",
"shadi movie pics",
"shadi payments",
"shadi m diye",
"shadi movie",
"shadi slaami",
"shadi suit",
"shadi sweettravelling ",
"shadii card",
"shadi  ar rent",
"bari makeup",
"bari shopping",
"jahez shopping",
"engagement shopping",
"bari",
"engagement"
)
}
