Allowance_Bonus=["ac daily allowance",
"allowance",
"allowance gift",
"allowance incentive",
"allowance javedan",
"audit allowance",
"bonus",
"conveyance allowance",
"daily allowance",
"festival bonus",
"house allowance",
"incentive bonus",
"legend allowance",
"monthly allowance",
"pol allowance",
"weekly allowance",
"weekly bonus",

                 ]