Other_Income=["academy income",
"agriculture income",
"other income"              
"amc income",
"amliyaat income",
"ana income",
"bc income",
"bday income",
"bickya income",
"bkash transfer income",
"business income",
"bussiness income",
"cafe income",
"car income",
"car income bs",
"car income other",
"clinic income",
"counter incoming fry burger",
"daily incom",
"daily income",
"daily office income",
"daraz cheque income",
"day time income",
"dividend income",
"drive income",
"eaton income",
"eid income",
"equity income",
"extra income",
"extra ssuet income",
"farm income",
"father income",
"fee income",
"flat rent income",
"freelance income",
"general income",
"genset income",
"ghar rent income",
"gift income",
"gold income",
"home income",
"house hold incom",
"house income",
"incom",
"income",
"income boy hostel",
"income girl hostel",
"income headoffice",
"income pet",
"income sp",
"income tax",
"income tax h g builder developer",
"incomeshop",
"incoming",
"incoming sale",
"incomr",
"internet income",
"kaam ki income",
"malaika income",
"mess income",
"mindoktor clinic income",
"mindoktor income",
"misc income",
"misc income adjustment",
"mohsin income",
"money exchange business income",
"monthly income",
"murtaza income",
"my income",
"net income",
"office income",
"old income",
"orbit business income",
"other incom",
"other income",
"other income bank account",
"papa clinic income",
"papa income",
"papa income clinic",
"pathao incom",
"per day income",
"pet income",
"photography income",
"pool income",
"rent income",
"rent incoming",
"rental income",
"ride income",
"salahuddin income",
"school income",
"shahzad income",
"shireen income",
"shop daily income",
"shop incom",
"shop income",
"stipend income",
"taha income",
"tejas income",
"total income",
"tq income",
"tractor income",
"tution income",
"umerkot zameen income",
"weekly income",
"workshop incom",
"workshop income",
"worshop incom",

]