Salary=["advance salary",
" salary",
" salary",
" salary",
" salary",
" salary",
"chef salary",
"cook salary",
"driver salary",
"emp salary",
"employee salary",
"employer salary",
"guard salary",
"help salary",
"kam salary",
"labour salary",
"lecture salary",
"masi salary",
"mjc salary",
"monthly salary",
"my salary",
"nexthome salary",
" salary",
"rem salary",
"salary",
"salary",
"salary advance",
"salary aisha",
"salary anum",
"salary dr",
"salary embassy",
"salary gem",
"salary mangal",
"salary paid",
"salary payment",
"salary pwd",
"salary self",
"salary snc",
"salary spouse",
"salary wage",
"salma salary",
"school salary",
"servant salary",
"shop salary",
"staff salary",
"sweeper salary",
"temp salary",
"tuition salary",
"umema salary per month",
"weekly salary",
 "Stipend",
 "stipend",
  "stippend",
   "stipent"

]
